name: ML7 Baseline

on:
  workflow_dispatch:

jobs:
  run-baseline:
    runs-on: ubuntu-latest
    env:                              # ← toma el secret y lo expone como env
      DATABASE_URL: ${{ secrets.SUPABASE_DB_URL }}
      WRITE_TO_SHADOW: "false"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "sqlalchemy==2.0.32" "psycopg2-binary==2.9.9" "scikit-learn==1.5.1" "pandas==2.2.2"

      - name: Assert DATABASE_URL (fail fast si falta)
        run: |
          if [ -z "${DATABASE_URL}" ]; then
            echo "❌ DATABASE_URL vacío. Cargá el secret SUPABASE_DB_URL en Settings → Secrets → Actions."
            exit 1
          fi
          echo "✅ DATABASE_URL presente (prefijo): ${DATABASE_URL%%:*}"

      - name: Run ML7 baseline
        run: python ml/baseline_ml7.py
