name: ML7 Baseline

on:
  workflow_dispatch:
  # opcional: corre todos los días a las 02:00 UTC
  schedule:
    - cron: "0 2 * * *"

jobs:
  run-baseline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "sqlalchemy==2.0.32" "psycopg2-binary==2.9.9" "scikit-learn==1.5.1" "pandas==2.2.2"

      - name: Run ML7 baseline
        env:
          DATABASE_URL: ${{ secrets.SUPABASE_DB_URL }}
          WRITE_TO_SHADOW: "false"   # poné "true" si querés copiar a match_model_scores (shadow)
        run: |
          python ml/baseline_ml7.py
